# Generated by Django 4.2 on 2023-04-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_22okt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festo',
            name='leltar',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kep',
            name='azon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
