# Generated by Django 4.2 on 2023-04-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_22okt', '0002_festo_leltar_kep_azon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festo',
            name='leltar',
        ),
        migrations.RemoveField(
            model_name='kep',
            name='azon',
        ),
        migrations.AddField(
            model_name='festo',
            name='azon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kep',
            name='leltar',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
